# Generated by Django 3.2.13 on 2022-06-23 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_model_update_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='Kód', max_length=10, unique=True)),
                ('name', models.CharField(blank=True, help_text='Název', max_length=100, null=True)),
                ('m5dg', models.CharField(blank=True, help_text='Členění na pátém místě', max_length=10, null=True)),
                ('type_character', models.CharField(blank=True, help_text='Znak pro označení druhu diagnózy (+*-)', max_length=10, null=True)),
                ('primary_diagnosis_dg', models.CharField(blank=True, help_text='Základní diagnóza v případě *Dg', max_length=10, null=True)),
                ('death_cause', models.CharField(blank=True, help_text='Skupina diagnóz příčin smrti', max_length=10, null=True)),
                ('inadmissible_gender', models.CharField(blank=True, help_text='Nepřípustné pohlaví', max_length=10, null=True)),
                ('acceptable_gender', models.CharField(blank=True, help_text='Přípustné pohlaví', max_length=10, null=True)),
                ('age_from', models.CharField(blank=True, help_text='Věk od', max_length=10, null=True)),
                ('age_to', models.CharField(blank=True, help_text='Věk do', max_length=10, null=True)),
                ('diagnosis_class', models.CharField(blank=True, help_text='Třída diagnózy', max_length=10, null=True)),
                ('who_group_1', models.CharField(blank=True, help_text='Skupina diagnóz č. 1 WHO', max_length=10, null=True)),
                ('who_group_2', models.CharField(blank=True, help_text='Skupina diagnóz č. 2 WHO', max_length=10, null=True)),
                ('who_group_3', models.CharField(blank=True, help_text='Skupina diagnóz č. 3 WHO', max_length=10, null=True)),
                ('who_group_4', models.CharField(blank=True, help_text='Skupina diagnóz č. 4 WHO', max_length=10, null=True)),
                ('who_group_5', models.CharField(blank=True, help_text='Skupina diagnóz č. 5 WHO', max_length=10, null=True)),
                ('ncd_diagnosis_group', models.CharField(blank=True, help_text='Skupina diagnóz pro NZIS', max_length=10, null=True)),
                ('skupla_1', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_2', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_3', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_4', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_5', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_6', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_7', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_8', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_9', models.CharField(blank=True, max_length=10, null=True)),
                ('mkn_conversion', models.CharField(blank=True, help_text='Převod na dg MKN-9', max_length=10, null=True)),
                ('valid_from', models.DateField(blank=True, help_text='Platnost od', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Platnost do', null=True)),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDiagnosis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(db_index=True, help_text='Kód', max_length=10)),
                ('name', models.CharField(blank=True, help_text='Název', max_length=100, null=True)),
                ('m5dg', models.CharField(blank=True, help_text='Členění na pátém místě', max_length=10, null=True)),
                ('type_character', models.CharField(blank=True, help_text='Znak pro označení druhu diagnózy (+*-)', max_length=10, null=True)),
                ('primary_diagnosis_dg', models.CharField(blank=True, help_text='Základní diagnóza v případě *Dg', max_length=10, null=True)),
                ('death_cause', models.CharField(blank=True, help_text='Skupina diagnóz příčin smrti', max_length=10, null=True)),
                ('inadmissible_gender', models.CharField(blank=True, help_text='Nepřípustné pohlaví', max_length=10, null=True)),
                ('acceptable_gender', models.CharField(blank=True, help_text='Přípustné pohlaví', max_length=10, null=True)),
                ('age_from', models.CharField(blank=True, help_text='Věk od', max_length=10, null=True)),
                ('age_to', models.CharField(blank=True, help_text='Věk do', max_length=10, null=True)),
                ('diagnosis_class', models.CharField(blank=True, help_text='Třída diagnózy', max_length=10, null=True)),
                ('who_group_1', models.CharField(blank=True, help_text='Skupina diagnóz č. 1 WHO', max_length=10, null=True)),
                ('who_group_2', models.CharField(blank=True, help_text='Skupina diagnóz č. 2 WHO', max_length=10, null=True)),
                ('who_group_3', models.CharField(blank=True, help_text='Skupina diagnóz č. 3 WHO', max_length=10, null=True)),
                ('who_group_4', models.CharField(blank=True, help_text='Skupina diagnóz č. 4 WHO', max_length=10, null=True)),
                ('who_group_5', models.CharField(blank=True, help_text='Skupina diagnóz č. 5 WHO', max_length=10, null=True)),
                ('ncd_diagnosis_group', models.CharField(blank=True, help_text='Skupina diagnóz pro NZIS', max_length=10, null=True)),
                ('skupla_1', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_2', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_3', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_4', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_5', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_6', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_7', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_8', models.CharField(blank=True, max_length=10, null=True)),
                ('skupla_9', models.CharField(blank=True, max_length=10, null=True)),
                ('mkn_conversion', models.CharField(blank=True, help_text='Převod na dg MKN-9', max_length=10, null=True)),
                ('valid_from', models.DateField(blank=True, help_text='Platnost od', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Platnost do', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='references.diagnosis')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical Diagnosis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
