# Generated by Django 3.2.12 on 2022-04-04 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreportvariable',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreportvariable',
            name='report_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.genericreporttype'),
        ),
        migrations.AddField(
            model_name='historicalreportvariable',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update'),
        ),
        migrations.AddField(
            model_name='historicalgenericreportfile',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='reports.genericreportfile'),
        ),
        migrations.AddField(
            model_name='historicalgenericreportfile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgenericreportfile',
            name='report_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.genericreporttype'),
        ),
        migrations.AddField(
            model_name='historicalgenericreportfile',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update'),
        ),
        migrations.AddField(
            model_name='genericreportfile',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.genericreporttype'),
        ),
        migrations.AlterUniqueTogether(
            name='reportvariable',
            unique_together={('report_type', 'description'), ('report_type', 'name')},
        ),
    ]
