# Generated by Django 3.2.13 on 2022-06-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_diagnoses'),
        ('requisitions', '0002_requisition_updated_at_auto_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisition',
            name='clinic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.clinic'),
        ),
        migrations.AddField(
            model_name='historicalrequisition',
            name='diagnosis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.diagnosis'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='references.clinic'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='references.diagnosis'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='requisitions.patient'),
        ),
    ]
